### PR TITLE
Updating npm packages

### PR DESCRIPTION
**Pull request by karbassi**
Can someone test this?

### CODE REVIEW

**Comment by karbassi** [comment]
CC: @floetenbaer @JOT85 @sadmin91 @luixal

**Comment by luixal** [comment]
Sorry, no longer using netatmo :(

**Comment by karbassi** [comment]
@floetenbaer Could you test this branch?

**Comment by floetenbaer** [comment]
@karbassi : Tested with ssadams11/node-red-contrib-netatmo#development. Works.

**Pull request merged**
