### PR TITLE
use error-message instead of error-object

### PR DESCRIPTION
**Pull request by janhuddel**
A little fix for a correct error-message:
before: getMeasure error: [object Object]
now: getMeasure error: Device not found

### CODE REVIEW

**Comment by karbassi** [comment]
@janhuddel does `errorMessage.error` always have `message`? 

Maybe change it to

```js
errorMessage = errorMessage && (errorMessage.error.message || errorMessage.error);
```

I'm coding from memory. Test to see if that works.

**Comment by janhuddel** [comment]
Yes, I can change it but netatmo currently sends an error-object with code and message on any failing request (see https://dev.netatmo.com/doc/methods). But perhaps they will change it in future, so your suggestion is more robust ;)

**Comment by karbassi** [comment]
@janhuddel good to know. I haven't worked on netatmo in a little while. The Open Source community, like yourself, has been submitting fixes, which is appreciated. 

If you want to make the changes and then I'll merge it in.

**Comment by janhuddel** [comment]
Hi,
here is the correct version...

**Pull request merged**
