### PR TITLE
Added getThermostatsData

### PR DESCRIPTION
**Pull request by marcuspocus**
Also added some minimal jsdoc comment and marked deprecated methods with @deprecated

### CODE REVIEW

**Comment by karbassi** [comment]
the JSDoc comments are most welcome.
Keep the 2 spaces since it's project standard.

I'll merge it in once the spacing is reverted back.

**Comment by marcuspocus** [comment]
Looking good now.

**Comment by karbassi** [comment]
Line 366 should be:

```javascript
this.emit('get-thermostatsdata', err, devices);
```

**Comment by marcuspocus** [comment]
Done fixing... Are you OK with it?
It's working great on my `homebridge-netatmo` setup atm...

`homebridge-netatmo` didn't have `netatmo-thermostats`support, and i needed the `getThermostatsData` in this `netatmo` lib for implementing it...

**Comment by karbassi** [comment]
Looks great! Thanks for the PR!

**Pull request merged**
