### PR TITLE
Prevent type error when response of a request is empty (e.g. internet connection failure)

### PR DESCRIPTION
**Pull request by danilowanner**
This is a fix for the following issue: https://github.com/karbassi/netatmo/issues/4

I have been testing my fork for 5 continuous days without a hitch.

This pull request also improves error events by emitting non-critical errors as a "warning"-event instead of an "error"-event which has a more appropriate default behavior (fails silently, without crashing the app). The error is also returned to callback function as first parameter (according to error-first paradigm; previously no callback was invoked).

### CODE REVIEW

**Comment by karbassi** [comment]
@danilowanner Can you create a branch so I can do some testing before merging?

Thanks for the PR!

**Comment by danilowanner** [comment]
@karbassi would you like to merge my master into a branch in your repo? Am I correct that in this case you would have to create that branch? Or should I create a branch in my fork? (I guess it’s a bit too late for that. But I should have done that probably.)

**Comment by karbassi** [comment]
@danilowanner Create a branch on your repo. It's not too late to do that. Rollback, create a branch, then commit the commits to that branch.

Merging master to master isn't a good idea.

**Comment by danilowanner** [comment]
@karbassi Okay thanks, I did that. The new branch is here: https://github.com/danilowanner/netatmo/tree/errorhandling

Should I create a new pull request?

**Comment by karbassi** [comment]
Yes please.

**Pull request closed without merging**
