### PR TITLE
Add smokedetector in scope

### PR DESCRIPTION
**Pull request by floetenbaer**

### CODE REVIEW

**Comment by karbassi** [comment]
@floetenbaer Thank you! 

Would you mind adding (writing) the smokedetector code/function in this PR?

**Comment by floetenbaer** [comment]
@karbassi : My PR based on an PR in my fork. The api (/gethomesdata, https://dev.netatmo.com/apidocumentation/security#homesdata) returns status information for smokedetectors without change.

**Comment by karbassi** [comment]
@floetenbaer, I'm looking to rewrite the package to bring it up to 2022 standards, however I do not have any of the devices.

Do you mind testing the new (upcoming) branch?

**Comment by floetenbaer** [comment]
@karbassi: yes, no problem.

**Pull request merged**
